In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3,4,5])
array1

array([1, 2, 3, 4, 5])

In [3]:
array1.ndim

1

In [4]:
array1.size

5

In [6]:
array1.dtype

dtype('int64')

In [8]:
array1.shape

(5,)

In [10]:
array1[[-1]]

array([5])

In [13]:
array2=np.array([[1,2,3],[4,5,6]])
array2
array2.ndim


2

In [17]:
array=np.arange(2,10)
array

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)   # addition
print(a - b)   # substraction
print(a * b)   # multiplication
print(a / b)   # division
print(a ** 2)  # square


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
